Controllers/ElectronicsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ManagementSystem.Models;

namespace ManagementSystem.Controllers
{

    public class ElectronicsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        [Authorize(Roles = "IT-spec")]
        public ActionResult Balanced()
        {
            return View(Misc.GetAllElectronics());
        }
        [Authorize(Roles = "IT-spec")]
        public ActionResult Ordered()
        {
            return View(Misc.GetAllElectronics());
        }
        [Authorize(Roles ="IT-spec, HR-manager")]
        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Electronics electronics = db.Electronics.Find(id);
            if (electronics == null)
            {
                return HttpNotFound();
            }
            return View(electronics);
        }
        [Authorize(Roles = "IT-spec,HR-manager")]
        public ActionResult Create()
        {
            return View();
        }
        [Authorize(Roles = "IT-spec,HR-manager")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,SerialNumber,Title,CPU,RAM,DiskSize,DiskType,Video,OS")] Electronics electronics)
        {
            if (ModelState.IsValid)
            {
                electronics.Id = Guid.NewGuid();
                db.Electronics.Add(electronics);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(electronics);
        }
        [Authorize(Roles = "IT-spec")]
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Electronics electronics = db.Electronics.Find(id);
            if (electronics == null)
            {
                return HttpNotFound();
            }
            return View(electronics);
        }
        [Authorize(Roles = "IT-spec")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,SerialNumber,Title,CPU,RAM,DiskSize,DiskType,Video,OS")] Electronics electronics)
        {
            if (ModelState.IsValid)
            {
                db.Entry(electronics).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(electronics);
        }
        [Authorize(Roles = "IT-spec")]
        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Electronics electronics = db.Electronics.Find(id);
            if (electronics == null)
            {
                return HttpNotFound();
            }
            return View(electronics);
        }
        [Authorize(Roles = "IT-spec")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            Electronics electronics = db.Electronics.Find(id);
            db.Electronics.Remove(electronics);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        [Authorize(Roles = "IT-spec")]
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/RequestsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ManagementSystem.Models;
using Microsoft.AspNet.Identity;

namespace ManagementSystem.Controllers
{
    public class RequestsController : Controller
    {
        private static ApplicationDbContext db = new ApplicationDbContext();

        // GET: Requests
        public ActionResult Index()
        {
            db = new ApplicationDbContext();
            return View(db.Requests.ToList());
        }

        // GET: Requests/Details/5
        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Requests requests = db.Requests.Find(id);
            if (requests == null)
            {
                return HttpNotFound();
            }
            return View(requests);
        }

        // GET: Requests/Create
        public ActionResult Create()
        {
            db = new ApplicationDbContext();
            ViewBag.Users = db.Users.Select(x => new SelectListItem()
            {
                Selected = false,
                Text = x.LastName + " " + x.FirstName + " " + x.MiddleName,
                Value = x.Id.ToString()
            }).ToList();
            return View();
        }

        // POST: Requests/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,UserId,DocName,ProcessType,Status")] Requests requests, HttpPostedFileBase File)
        {
            db = new ApplicationDbContext();
            if (ModelState.IsValid)
            {
                requests.Id = Guid.NewGuid();
                requests.StartedDate = DateTime.Now;
                var user = Misc.GetUser(requests.UserId.ToString());
                requests.UserFIO = user.GetUserFullname();
                var executor = Misc.GetUser(User.Identity.GetUserId());
                requests.ExecutorId = new Guid(executor.Id);
                requests.ExecutorFIO = executor.GetUserFullname();
                string generatename = requests.ProcessType + "_" + requests.StartedDate.ToString("HH-mm-ss_dd.MM.yyyy");
                if (File != null && File.ContentLength > 0)
                    requests.DocUrl = Misc.SaveFileToUser(File, requests.UserId.ToString(), generatename);
                else
                    goto next;
                requests.Status = "На рассмотрении";

                db.Requests.Add(requests);
                db.SaveChanges();
                return RedirectToAction("Resumes");
            }
        next:

            ViewBag.Users = db.Users.Select(x => new SelectListItem()
            {
                Selected = false,
                Text = x.LastName + " " + x.FirstName + " " + x.MiddleName,
                Value = x.Id.ToString()
            }).ToList();
            return View(requests);
        }

        // GET: Requests/Edit/5
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Requests requests = db.Requests.Find(id);
            if (requests == null)
            {
                return HttpNotFound();
            }
            return View(requests);
        }

        // POST: Requests/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,StartedDate,FinishedDate,UserId,ExecutorId,SignerId,SignedDate,DocName,DocUrl,ProcessType,Status")] Requests requests)
        {
            if (ModelState.IsValid)
            {
                db.Entry(requests).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(requests);
        }

        // GET: Requests/Delete/5
        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Requests requests = db.Requests.Find(id);
            if (requests == null)
            {
                return HttpNotFound();
            }
            return View(requests);
        }

        // POST: Requests/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            Requests requests = db.Requests.Find(id);
            db.Requests.Remove(requests);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult Resumes()
        {
            var requests = new ApplicationDbContext().Requests.ToList();
            if (requests.Count() > 0)
            {
                var data = requests
                    .Where(p => p.ProcessType.Equals("Resumes") && p.ExecutorId.ToString().Equals(User.Identity.GetUserId()))
                    .OrderByDescending(t => t.StartedDate)
                    .ToList();

                return View(data);
            }
            return View(new List<Requests>());
        }
        public ActionResult Contracts()
        {
            var requests = new ApplicationDbContext().Requests.ToList();
            if (requests.Count() > 0)
            {
                var data = requests
                .Where(p => p.ProcessType.Equals("Contracts") && p.ExecutorId.ToString().Equals(User.Identity.GetUserId()))
                .OrderByDescending(t => t.StartedDate)
                .ToList();

                return View(data);
            }
            return View(new List<Requests>());
        }
        public ActionResult Applications()
        {
            var requests = new ApplicationDbContext().Requests.ToList();
            if (requests.Count() > 0)
            {
                var data = requests
                .Where(p => p.ProcessType.Equals("Applications") && p.ExecutorId.ToString().Equals(User.Identity.GetUserId()))
                .OrderByDescending(t => t.StartedDate)
                .ToList();

                return View(data);
            }
            return View(new List<Requests>());
        }
    }
}

Controllers/RolesAdminController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using ManagementSystem;
using ManagementSystem.Models;

namespace ManagementSystem.Controllers
{
    [Authorize(Roles = "HR-manager")]
    public class RolesAdminController : Controller
    {
        public RolesAdminController()
        {
        }

        public RolesAdminController(ApplicationUserManager userManager, ApplicationRoleManager roleManager)
        {
            UserManager = userManager;
            RoleManager = roleManager;
        }

        private ApplicationUserManager _userManager;
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            set
            {
                _userManager = value;
            }
        }

        private ApplicationRoleManager _roleManager;
        public ApplicationRoleManager RoleManager
        {
            get
            {
                var approlemanager = HttpContext.GetOwinContext().Get<ApplicationRoleManager>();
                return _roleManager ?? approlemanager; 
            }
            private set
            {
                _roleManager = value;
            }
        }

        //
        // GET: /Roles/
        [HttpGet]
        public ActionResult Index()
        {
            ApplicationDbContext db = new ApplicationDbContext();
            return View(db.Roles);
            //if(RoleManager!=null)
            //    return View(RoleManager.Roles);
            //return View();
        }

        //
        // GET: /Roles/Details/5
        [HttpGet]
        public async Task<ActionResult> Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var role = await RoleManager.FindByIdAsync(id);
            // Get the list of Users in this Role
            var users = new List<ApplicationUser>();

            // Get the list of Users in this Role
            foreach (var user in UserManager.Users.ToList())
            {
                if (await UserManager.IsInRoleAsync(user.Id, role.Name))
                {
                    users.Add(user);
                }
            }

            ViewBag.Users = users;
            ViewBag.UserCount = users.Count();
            return View(role);
        }

        //
        // GET: /Roles/Create
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Roles/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(RoleViewModel roleViewModel)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var role = new IdentityRole(roleViewModel.Name);
                    var roleresult = await RoleManager.CreateAsync(role);
                    if (!roleresult.Succeeded)
                    {
                        ModelState.AddModelError("", roleresult.Errors.First());
                        return View();
                    }
                    return RedirectToAction("Index");
                }
                catch(Exception ex)
                {
                    ModelState.AddModelError("", ex.Message);
                    return View(roleViewModel); 
                }
            }
            return View();
        }

        //
        // GET: /Roles/Edit/Admin
        [HttpGet]
        public async Task<ActionResult> Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var role = await RoleManager.FindByIdAsync(id);
            if (role == null)
            {
                return HttpNotFound();
            }
            RoleViewModel roleModel = new RoleViewModel { Id = role.Id, Name = role.Name };
            return View(roleModel);
        }

        //
        // POST: /Roles/Edit/5
        [HttpPost]

        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Name,Id")] RoleViewModel roleModel)
        {
            if (ModelState.IsValid)
            {
                var role = await RoleManager.FindByIdAsync(roleModel.Id);
                role.Name = roleModel.Name;
                await RoleManager.UpdateAsync(role);
                return RedirectToAction("Index");
            }
            return View();
        }

        //
        // GET: /Roles/Delete/5
        [HttpGet]
        public async Task<ActionResult> Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var role = await RoleManager.FindByIdAsync(id);
            if (role == null)
            {
                return HttpNotFound();
            }
            return View(role);
        }

        //
        // POST: /Roles/Delete/5
        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(string id, string deleteUser)
        {
            if (ModelState.IsValid)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                var role = await RoleManager.FindByIdAsync(id);
                if (role == null)
                {
                    return HttpNotFound();
                }
                IdentityResult result;
                if (deleteUser != null)
                {
                    result = await RoleManager.DeleteAsync(role);
                }
                else
                {
                    result = await RoleManager.DeleteAsync(role);
                }
                if (!result.Succeeded)
                {
                    ModelState.AddModelError("", result.Errors.First());
                    return View();
                }
                return RedirectToAction("Index");
            }
            return View();
        }
    }
}

Views/Shared/_AccountLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>ManagementSystem | @ViewBag.Title</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.5 -->
    <link rel="stylesheet" href="~/Content/bootstrap.min.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/Content/dist/css/AdminLTE.min.css">
    <!-- iCheck -->
    <link rel="stylesheet" href="~/Content/plugins/iCheck/square/blue.css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body class="hold-transition login-page">
    <div class="login-box">
        <div class="login-logo">
            <a href="~/Home/Index"><b>Management</b>System</a>
        </div>
        @RenderBody()
    </div><!-- /.login-box -->
    @Scripts.Render("~/bundles/jqueryval")
    <!-- jQuery 2.1.4 -->
    <script src="~/Content/plugins/jQuery/jQuery-2.1.4.min.js"></script>
    <!-- Bootstrap 3.3.5 -->
    <script src="~/Scripts/bootstrap.min.js"></script>
    <!-- iCheck -->
    <script src="~/Content/plugins/iCheck/icheck.min.js"></script>
    <script>
        $(function () {
            $('input').iCheck({
                checkboxClass: 'icheckbox_square-blue',
                radioClass: 'iradio_square-blue',
                increaseArea: '20%' // optional
            });
        });
    </script>
</body>
</html>

Views/Shared/_MainLayout.cshtml
@using Microsoft.AspNet.Identity
@using ManagementSystem.Models;
@{
    ApplicationUser currentUser;
    if (User.Identity.IsAuthenticated)
    {
        currentUser = Misc.GetUser(User.Identity.GetUserId());
    }
    else
    {
        throw new Exception("");
    }
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>ManagementSystem | @ViewBag.Title</title>
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <link rel="stylesheet" href="~/Content/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="~/Content/dist/css/AdminLTE.min.css">
    <link rel="stylesheet" href="~/Content/dist/css/skins/_all-skins.min.css">
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <link href="~/Content/Site.css" rel="stylesheet" />
</head>
<body class="hold-transition skin-blue sidebar-mini">
    <div class="wrapper">
        <header class="main-header">
            <!-- Logo -->
            <a href="@Url.Action("Index","Manage")" class="logo">
                <span class="logo-mini"><b>M</b>S</span>
                <span class="logo-lg"><b>Management</b>System</span>
            </a>
            <nav class="navbar navbar-static-top" role="navigation">
                <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </a>
                <div class="navbar-custom-menu">
                    <ul class="nav navbar-nav">

                        <!-- Аккаунт -->
                        <li class="dropdown user user-menu">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                @if (string.IsNullOrEmpty(currentUser.Photo))
                                {<img src="~/Content/dist/img/no-photo.png" class="user-image" alt="Фото @currentUser.GetUserFullname() 1"> }
                                else
                                {<img src="@Url.Content(currentUser.Photo)" class="user-image" alt="Фото @currentUser.GetUserFullname() 1">}

                                <span class="hidden-xs">@currentUser.GetUserFullname()</span>
                            </a>
                            <ul class="dropdown-menu">
                                <!-- User image -->
                                <li class="user-header">
                                    @if (string.IsNullOrEmpty(currentUser.Photo))
                                    {<img src="~/Content/dist/img/no-photo.png" class="img-circle" alt="Фото @currentUser.GetUserFullname() 2"> }
                                    else
                                    {<img src="@Url.Content(currentUser.Photo)" class="img-circle" alt="Фото @currentUser.GetUserFullname() 2">}
                                    <p>
                                        @currentUser.GetUserFullname()
                                        <small>@currentUser.StartedDate.ToString("dd-MM-yyyy")</small>
                                    </p>
                                </li>
                                <!-- Menu Footer-->
                                <li class="user-footer">
                                    <div class="pull-left">
                                        <a href="@Url.Action("Index","Manage")" class="btn btn-default btn-flat">Профиль</a>
                                    </div>
                                    <div class="pull-right">
                                        @using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm", @class = "navbar-right" }))
                                        {
                                            @Html.AntiForgeryToken()
                                        }
                                        <a href="javascript:document.getElementById('logoutForm').submit()" class="btn btn-default btn-flat">Выйти</a>

                                    </div>
                                </li>
                            </ul>
                        </li>

                    </ul>
                </div>
            </nav>
        </header>

        <!-- =============================================== -->

        <aside class="main-sidebar">
            <section class="sidebar">
                <ul class="sidebar-menu">
                    <li class="header">ГЛАВНОЕ МЕНЮ</li>
                    @if (User.IsInRole("IT-spec"))
                    {
                        <li class="treeview">
                            <a href="#">
                                <i class="fa fa-dashboard"></i>
                                <span>Электроники</span>
                                <i class="fa fa-angle-left pull-right"></i>
                            </a>
                            <ul class="treeview-menu">
                                <li><a href="@Url.Action("Balanced", "Electronics")"><i class="fa fa-circle-o"></i> Закупленные</a></li>
                                <li><a href="@Url.Action("Ordered", "Electronics")"><i class="fa fa-circle-o"></i> На рассмотрении</a></li>
                            </ul>
                        </li>
                    }
                    @if (User.IsInRole("HR-manager"))
                    {
                        <li>
                            <a href="@Url.Action("Index", "RolesAdmin")">
                                <i class="fa fa-th"></i>
                                <span>Роли</span>
                                <small class="label pull-right bg-green">@Misc.GetRolesCount()</small>
                            </a>
                        </li>
                        <li>
                            <a href="@Url.Action("Index", "UsersAdmin")">
                                <i class="fa fa-th"></i>
                                <span>Пользователи</span>
                                <small class="label pull-right bg-green">@Misc.GetUsersCount()</small>
                            </a>
                        </li>

                    }
                    <li><a href="@Url.Action("Resumes","Requests")"><i class="fa fa-circle-o text-red"></i><span>Резюме</span></a></li>
                    <li><a href="@Url.Action("Contracts","Requests")"><i class="fa fa-circle-o text-yellow"></i><span>Договора</span></a></li>
                    <li><a href="@Url.Action("Applications","Requests")"><i class="fa fa-circle-o text-aqua"></i><span>Приказы</span></a></li>
                    <li><a href="@Url.Action("Create","Requests")"><i class="fa fa-plus text-gray"></i><span>создать</span></a></li>
                </ul>
            </section> 
        </aside>

        @RenderBody()

        <footer class="main-footer">
            <div class="pull-right hidden-xs">
                <b>Version</b> 1.0 <span>@Misc.MachineName</span>
            </div>
            <strong>Copyright &copy; 2014-2022 Все права защищены. </strong>
        </footer> 
    </div>

    <script src="~/Content/plugins/jQuery/jQuery-2.1.4.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Content/plugins/slimScroll/jquery.slimscroll.min.js"></script>
    <script src="~/Content/plugins/fastclick/fastclick.min.js"></script>
    <script src="~/Content/dist/js/app.min.js"></script>
    <script src="~/Content/dist/js/demo.js"></script>

    @RenderSection("scripts", required: false)
</body>
</html> 