Controllers/ElectronicsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ManagementSystem.Models;

namespace ManagementSystem.Controllers
{

    public class ElectronicsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        [Authorize(Roles = "IT-spec")]
        public ActionResult Balanced()
        {
            return View(Misc.GetAllElectronics());
        }
        [Authorize(Roles = "IT-spec")]
        public ActionResult Ordered()
        {
            return View(Misc.GetAllElectronics());
        }
        [Authorize(Roles ="IT-spec, HR-manager")]
        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Electronics electronics = db.Electronics.Find(id);
            if (electronics == null)
            {
                return HttpNotFound();
            }
            return View(electronics);
        }
        [Authorize(Roles = "IT-spec,HR-manager")]
        public ActionResult Create()
        {
            return View();
        }
        [Authorize(Roles = "IT-spec,HR-manager")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,SerialNumber,Title,CPU,RAM,DiskSize,DiskType,Video,OS")] Electronics electronics)
        {
            if (ModelState.IsValid)
            {
                electronics.Id = Guid.NewGuid();
                db.Electronics.Add(electronics);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(electronics);
        }
        [Authorize(Roles = "IT-spec")]
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Electronics electronics = db.Electronics.Find(id);
            if (electronics == null)
            {
                return HttpNotFound();
            }
            return View(electronics);
        }
        [Authorize(Roles = "IT-spec")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,SerialNumber,Title,CPU,RAM,DiskSize,DiskType,Video,OS")] Electronics electronics)
        {
            if (ModelState.IsValid)
            {
                db.Entry(electronics).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(electronics);
        }
        [Authorize(Roles = "IT-spec")]
        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Electronics electronics = db.Electronics.Find(id);
            if (electronics == null)
            {
                return HttpNotFound();
            }
            return View(electronics);
        }
        [Authorize(Roles = "IT-spec")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            Electronics electronics = db.Electronics.Find(id);
            db.Electronics.Remove(electronics);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        [Authorize(Roles = "IT-spec")]
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/UsersAdminController.cs
using ManagementSystem.Models;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace ManagementSystem.Controllers
{ 
    [Authorize(Roles = "HR-manager")]
    public class UsersAdminController : Controller
    {
        public ApplicationDbContext db = new ApplicationDbContext();
        public UsersAdminController()
        {
        }

        public UsersAdminController(ApplicationUserManager userManager, ApplicationRoleManager roleManager)
        {
            UserManager = userManager;
            RoleManager = roleManager;
        }

        private ApplicationUserManager _userManager;
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        private ApplicationRoleManager _roleManager;
        public ApplicationRoleManager RoleManager
        {
            get
            {
                return _roleManager ?? HttpContext.GetOwinContext().Get<ApplicationRoleManager>();
            }
            private set
            {
                _roleManager = value;
            }
        }

        //
        // GET: /Users/
        [HttpGet]
        public async Task<ActionResult> Index()
        {
            return View(await UserManager.Users.ToListAsync());
        }
         

        //
        // GET: /Users/Create
        [HttpGet]
        public async Task<ActionResult> Create()
        {
            //Get the list of Roles
            ViewBag.RoleId = new SelectList(await RoleManager.Roles.ToListAsync(), "Name", "Name");
            return View();
        }

        //
        // POST: /Users/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(RegisterViewModel userViewModel, params string[] selectedRoles)
        {
            if (ModelState.IsValid)
            {
                var user = new ApplicationUser { 
                    UserName = userViewModel.Email, 
                    Email = userViewModel.Email,
                    FirstName= userViewModel.FirstName,
                    LastName= userViewModel.LastName,
                    MiddleName= userViewModel.MiddleName,
                    Department= userViewModel.Department,
                    Position= userViewModel.Position,
                    StartedDate= DateTime.Now.Date
                };
                 
                var adminresult = await UserManager.CreateAsync(user, "Test1234!");

                await UserManager.SendEmailAsync(user.Id, "Регистрация", "Ваш пароль: Test1234!");

                //Add User to the selected Roles 
                if (adminresult.Succeeded)
                {
                    if (selectedRoles != null)
                    {
                        var result = await UserManager.AddToRolesAsync(user.Id, selectedRoles);
                        if (!result.Succeeded)
                        {
                            ModelState.AddModelError("", result.Errors.First());
                            ViewBag.RoleId = new SelectList(await RoleManager.Roles.ToListAsync(), "Name", "Name");
                            return View();
                        }
                    }
                }
                else
                {
                    ModelState.AddModelError("", adminresult.Errors.First());
                    ViewBag.RoleId = new SelectList(RoleManager.Roles, "Name", "Name");
                    return View();
                }
                return RedirectToAction("Index");
            }
            ViewBag.RoleId = new SelectList(RoleManager.Roles, "Name", "Name");
            return View();
        }
         
        //
        // GET: /Users/AddElectronic/1
        [HttpGet]
        public async Task<ActionResult> AddElectronic(string id)
        {
            if (id == null) 
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest); 
            ApplicationUser user = await UserManager.FindByIdAsync(id);
            if (user == null) 
                return HttpNotFound();
             
            return View(new AddElectronicToUserViewModel()
            {
                UserInfo = user,
                UserId = user.Id, 
                ElectronicsList = Misc.GetAllElectronics().Select(x => new SelectListItem()
                {
                    Selected = false,
                    Text = x.Title+" ("+x.SerialNumber+")",
                    Value = x.Id.ToString()
                })
            });
        }

        //
        // POST: /Users/AddElectronic/1
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> AddElectronic([Bind(Include = "UserId")] AddElectronicToUserViewModel addElectronic, string SelectedElectronics)
        {
            addElectronic.ElectronicsList  = Misc.GetAllElectronics().Select(x => new SelectListItem()
            {
                Selected = false,
                Text = x.Title + " (" + x.SerialNumber + ")",
                Value = x.Id.ToString()
            });
            addElectronic.UserInfo = Misc.GetUser(addElectronic.UserId);
            var electronic = Misc.GetElectronics(SelectedElectronics); 
            if (electronic == null)
            {
                ModelState.AddModelError("", "Пожалуйста выберите электронику");
                return View(addElectronic); 
            }
            
            if (ModelState.IsValid)
            {  
                try
                {
                    electronic.ApplicationUser = addElectronic.UserInfo;
                    electronic.UserId = new Guid(addElectronic.UserId); 
                    db.Entry(electronic).State = EntityState.Modified;
                    db.SaveChanges(); 
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", ex.Message);
                    return View(addElectronic);
                }
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", "Что-то произошло не так.");
            return View(addElectronic);
        }


        public ActionResult Add(Guid? id)
        {
            ViewBag.Users = db.Users.Select(x => new SelectListItem()
            {
                Selected = false,
                Text = x.LastName + " " + x.FirstName + " " + x.MiddleName,
                Value = x.Id.ToString()
            }).ToList();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Electronics electronics = db.Electronics.Find(id);
            if (electronics == null)
            {
                return HttpNotFound();
            }
            return View(electronics);
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Add([Bind(Include = "Id,SerialNumber,Title,CPU,RAM,DiskSize,DiskType,Video,OS,UserId")] Electronics electronics)
        {  
            if (ModelState.IsValid)
            {
                db.Entry(electronics).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(electronics);
        }
        //
        // GET: /Users/Details/1
        [HttpGet]
        public async Task<ActionResult> Details(string id)
        {
            if (id == null) 
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            
            var user = await UserManager.FindByIdAsync(id);
            if (user == null) 
                return HttpNotFound();
            
            var userRoles = await UserManager.GetRolesAsync(user.Id);
            var electronics = Misc.GetUserElectronics(user.Id);
            return View(new DetailsUserViewModel()
            {
                UserInfo = user,
                Electronics = electronics,
                RolesList = RoleManager.Roles.ToList().Select(x => new SelectListItem()
                {
                    Selected = userRoles.Contains(x.Name),
                    Text = x.Name,
                    Value = x.Name
                })
            });
        }

        //
        // GET: /Users/Details/5
        [HttpGet]
        public async Task<ActionResult> Details2(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var user = await UserManager.FindByIdAsync(id);
            ViewBag.RoleNames = await UserManager.GetRolesAsync(user.Id);
            return View(user);
        }

        //
        // GET: /Users/Edit/1
        [HttpGet]
        public async Task<ActionResult> Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var user = await UserManager.FindByIdAsync(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            var userRoles = await UserManager.GetRolesAsync(user.Id);
            return View(new ExtraEditUserViewModel()
            {
                Id = user.Id,
                Email = user.Email,
                LastName = user.LastName,
                FirstName = user.FirstName,
                MiddleName = user.MiddleName,
                BirthDate = user.BirthDate,
                Department = user.Department,
                Position = user.Position,
                Photo = user.Photo,

Views/UsersAdmin/Add.cshtml
@model ManagementSystem.Models.Electronics

@{
    ViewBag.Title = "Добавление электроники";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
    List<SelectListItem> selectLists = ViewBag.Users;
}
<!-- =============================================== --> 
<section class="content-wrapper">

    <section class="content-header">
        <h1>
            @ViewBag.Title
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Главное</a></li>
            <li><a href="#">Профиль</a></li>
        </ol>
    </section>

    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="box box-primary">
                    <div class="box-body">

                        @using (Html.BeginForm())
                        {
                            @Html.AntiForgeryToken() 
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            @Html.HiddenFor(model => model.Id)
                            @Html.HiddenFor(model => model.SerialNumber)
                            @Html.HiddenFor(model => model.Title)
                            @Html.HiddenFor(model => model.CPU)
                            @Html.HiddenFor(model => model.RAM)
                            @Html.HiddenFor(model => model.DiskSize)
                            @Html.HiddenFor(model => model.DiskType)
                            @Html.HiddenFor(model => model.Video)
                            @Html.HiddenFor(model => model.OS)
                        <div class="form-group"> 
                            <label for="UserId">Выберите работника</label>
                            @Html.DropDownListFor(model => model.UserId, selectLists, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
                        </div>

                            <div class="form-group">
                                <input type="submit" value="Save" class="btn btn-success" />
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </section>
</section>
<!-- =============================================== -->
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/UsersAdmin/AddElectronic.cshtml
@model ManagementSystem.Models.AddElectronicToUserViewModel
@using ManagementSystem.Models
@{
    ViewBag.Title = "Добавление электроники";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
    List<Electronics> electronics = ViewBag.Electronics;
}


<!-- =============================================== -->

<section class="content-wrapper">

    <section class="content-header">
        <h1>
            @ViewBag.Title
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Главное</a></li>
            <li><a href="#">Профиль</a></li>
        </ol>
    </section>

    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="box box-primary">
                    <div class="box-body">

                        @using (Html.BeginForm())
                        {
                            @Html.AntiForgeryToken() 
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            @Html.HiddenFor(model => model.UserId)

                        <select name="SelectedElectronics" class="form-control">
                            @{
                                var last = (Model.Electronics != null )
                                    ? Model.Electronics
                                    : null;
                                if (last == null)
                                {
                                    <option value="" selected>-</option>
                                }
                                foreach (var elc in Model.ElectronicsList)
                                {
                                    if (last != null && last.Id.ToString() == elc.Value)
                                    {
                                        <option value="@elc.Value" selected>@elc.Text</option>
                                    }
                                    else
                                    {
                                        <option value="@elc.Value">@elc.Text</option>
                                    }
                                }

                            }
                        </select>
                            <br />
                            <div class="form-group"> 
                                <input type="submit" value="Сохранить" class="btn btn-success" /> 
                            </div> 
                        }
                    </div>
                </div>
            </div>
        </div>
    </section>
</section>
<!-- =============================================== -->

Views/UsersAdmin/Create.cshtml
@model ManagementSystem.Models.RegisterViewModel
@{
    ViewBag.Title = "Создать пользователь";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}
<!-- =============================================== -->

<div class="content-wrapper">

    <section class="content-header">
        <h1>
            Пользователь
            <small>создание</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Главное</a></li>
            <li><a href="#">Пользователи</a></li>
            <li class="active">Создание</li>
        </ol>
    </section>

    <section class="content">
        <div class="row">
            <div class="col-md-12">
                <div class="box box-primary"> 
                    <div class="box-header with-border">
                        <h3 class="box-title">@ViewBag.Title</h3>
                        <div class="box-tools pull-right">
                            <button class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse"><i class="fa fa-minus"></i></button>
                            <button class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove"><i class="fa fa-times"></i></button>
                        </div> 
                    </div>
                    @using (Html.BeginForm("Create", "UsersAdmin", FormMethod.Post, new { role = "form" }))
                    {
                        @Html.AntiForgeryToken()
                        <div class="box-body">
                            <div class="form-group">
                                @Html.ValidationSummary("", new { @class = "text-error" })
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.LastName)
                                @Html.TextBoxFor(m => m.LastName, new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.FirstName)
                                @Html.TextBoxFor(m => m.FirstName, new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.MiddleName)
                                @Html.TextBoxFor(m => m.MiddleName, new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.MiddleName, "", new { @class = "text-danger" })
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Email)
                                @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Department)
                                <select class="form-control" name="Department" id="Department">
                                    <option value="" selected>Выберите департамент</option>
                                    <option value="HR-Department">HR отдел</option>
                                    <option value="IT-Department">IT отдел</option>
                                    <option value="Accountant">Бухгалтерия</option>
                                    <option value="Administration">Администрация</option>
                                </select>
                                @Html.ValidationMessageFor(model => model.Department, "", new { @class = "text-danger" })
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Position)
                                <select class="form-control" name="Position" id="Position">
                                    <option value="" selected>Выберите должность</option>
                                    <option value="HR-manager">HR менеджер</option>
                                    <option value="IT-spec">IT специалист</option>
                                    <option value="Accountant">Бухгалтер</option>
                                    <option value="Admin">Директор</option>
                                </select>
                                @Html.ValidationMessageFor(model => model.Position, "", new { @class = "text-danger" })
                            </div>

                            <div class="form-group">
                                <label>Выберите роль</label>
                                @foreach (var item in (SelectList)ViewBag.RoleId)
                                {
                                    <div class="checkbox">
                                        <label>
                                            <input type="checkbox" name="SelectedRole" value="@item.Value" checked="@item.Selected"> @Html.Label(item.Value, new { @class = "control-label" })
                                        </label>
                                    </div>
                                }
                            </div>
                        </div>
                        <div class="box-footer">
                            <a href="@Url.Action("Index")" class="btn btn-primary"><i class="fa fa-arrow-left" aria-hidden="true"></i> назад</a>
                            <button type="submit" class="btn btn-success pull-right">  сохранить <i class="fa fa-arrow-right" aria-hidden="true"></i></button>
                        </div>
                    }
                </div>
            </div>
        </div>
    </section>
</div>

Views/UsersAdmin/Details.cshtml
@model ManagementSystem.Models.DetailsUserViewModel
@{
    ViewBag.Title = Model.UserInfo.GetUserFullname();
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}
<!-- =============================================== -->

<section class="content-wrapper">

    <section class="content-header">
        <h1>
            @ViewBag.Title
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Главное</a></li>
            <li><a href="#">Пользватели</a></li>
        </ol>
    </section> 
    <section class="content">
        <div class="row">
            <div class="col-xs-6">
                <div class="box box-primary">
                    <div class="box-body box-profile">
                        @if (string.IsNullOrEmpty(Model.UserInfo.Photo))
                        {<img class="profile-user-img img-responsive img-circle" style="width:144px;height:144px;object-fit:cover;" src="~/Content/dist/img/no-photo.png" alt="User profile picture"> }
                        else
                        {<img class="profile-user-img img-responsive img-circle" style="width:144px;height:144px;object-fit:cover;" src="@Url.Content(Model.UserInfo.Photo)" alt="User profile picture">}
                        <h3 class="profile-username text-center">@Model.UserInfo.GetUserFullname()</h3>
                        <p class="text-muted text-center">
                            <br />
                        </p>
                        <ul class="list-group list-group-unbordered">
                            <li class="list-group-item">
                                <b>Отдел:</b>
                                @if (string.IsNullOrEmpty(Model.UserInfo.Department))
                                {<a class="pull-right">Не установлен</a>}
                                else
                                {<a class="pull-right">@Model.UserInfo.Department</a>}
                            </li>
                            <li class="list-group-item">
                                <b>Должность:</b>
                                @if (string.IsNullOrEmpty(Model.UserInfo.Position))
                                {<a class="pull-right">Не установлен</a>}
                                else
                                {<a class="pull-right">  @Model.UserInfo.Position</a>}
                            </li>
                            <li class="list-group-item">
                                <b>Работает с:</b>
                                @if (Model.UserInfo.StartedDate == new DateTime(1900, 1, 1))
                                {<a class="pull-right">Не установлен</a>}
                                else
                                {<a class="pull-right">@Convert.ToDateTime(Model.UserInfo.StartedDate).ToString("dd-MM-yyyy")</a>}
                            </li>
                        </ul>

                        <a href="#" class="btn btn-primary btn-block"><b>изменить</b></a>

                        <p class="text-success">@ViewBag.StatusMessage</p>

                    </div>
                </div>
            </div>

            <div class="col-xs-6">
                <div class="box box-primary">
                    <div class="box-body box-profile">

                        <table class="table">
                            <tr>
                                <th colspan="2">Роли</th>
                            </tr>
                            @if (Model.RolesList.Count(p => p.Selected) > 0)
                            {
                                foreach (var role in Model.RolesList.Where(p => p.Selected))
                                {
                                    <tr>
                                        <td>@role.Text</td>
                                    </tr>
                                }
                            }
                            <tr>
                                <th rowspan="2">Электроники</th>
                            </tr>
                            @if (Model.Electronics != null)
                            {
                                <tr>
                                    <td><a href="@Url.Action("Details","Electronics", new { id = Model.Electronics.Id})"> @Model.Electronics.SerialNumber (@Model.Electronics.OS) </a></td>
                                </tr> 
                            }
                            <tr>
                                <td rowspan="2"> <a href="@Url.Action("AddElectronic", new { Id = Model.UserInfo.Id })" class="btn btn-bitbucket btn-block"><b>Добавить</b></a></td>
                            </tr>
                        </table>

                    </div>
                </div>
            </div>

        </div>
    </section>

</section>

<!-- =============================================== -->